---
# NFS Mount Visualizer Configuration

# Prometheus server URL
prometheus_url: "http://localhost:9090"

# Refresh interval in seconds
refresh_interval: 300

# Cache directory for temporary files
cache_dir: ".cache"

# Application title
app_title: "NFS Mount Visualization"

# Prometheus metric name for NFS mount accessibility
metric_name: "nfs_mount_accessible"

# Metric label mapping - customize these based on your Prometheus metric structure
metric_mapping:
  server_label: "source_node"     # Label name for NFS server node
  client_label: "target_node"     # Label name for NFS client node
  path_label: "mount_path"        # Label name for mount path
  mount_path_prefix: "/mnt/"      # Prefix to add to mount paths in display

# List of cluster nodes to include in the visualization
cluster_nodes:
  - "node1"
  - "node2"
  - "node3"
  - "node4"
  - "storage1"
  - "storage2"

# Node types with custom colors and titles
node_types:
  default:
    color: "#607D8B"
    title: "Cluster Node"
  
  node1:
    color: "#6E9FED"
    title: "Head Node"
  
  node2:
    color: "#4CAF50"
    title: "Compute Node"
  
  node3:
    color: "#4CAF50"
    title: "Compute Node"
  
  node4:
    color: "#FF9800"
    title: "GPU Compute Node"
  
  storage1:
    color: "#9C27B0"
    title: "Storage Node"
  
  storage2:
    color: "#E91E63"
    title: "Storage Node"

# Visualization settings
visualization:
  # Network graph settings
  network:
    height: "700px"
    width: "100%"
    bgcolor: "#222222"
    font_color: "white"
    
  # Edge colors for mount status
  edge_colors:
    accessible: "#4CAF50"      # Green for accessible mounts
    inaccessible: "#F44336"    # Red for inaccessible mounts
    
  # Node sizing
  node_sizing:
    base_size: 25              # Base node size
    export_multiplier: 3       # Size increase per export
    
  # Network physics settings
  physics:
    gravity: -8000
    central_gravity: 0.3
    spring_length: 200
    
  # Chart settings
  charts:
    line_chart_height: 400